"use client"

import { AlertTriangle, TrendingUp, Droplets, Leaf, Target, CheckCircle } from "lucide-react"
import { LineChart, Line, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip } from "recharts"

export function AnalysisPreview({ result }: { result: any }) {
  if (!result) return null

  const isCrop = result.type === "crop"
  const analysis = result.analysis

  // Disease severity meter color
  const getSeverityColor = (severity: number) => {
    if (severity < 20) return "text-green-600"
    if (severity < 50) return "text-yellow-600"
    if (severity < 80) return "text-orange-600"
    return "text-red-600"
  }

  // NPK radar data for soil
  const npkData = isCrop
    ? [
      { name: "N", value: 70 },
      { name: "P", value: 45 },
      { name: "K", value: 65 },
    ]
    : analysis.npk
      ? [
        { name: "N", value: Math.min((analysis.npk.nitrogen / 300) * 100, 100) },
        { name: "P", value: Math.min((analysis.npk.phosphorus / 200) * 100, 100) },
        { name: "K", value: Math.min((analysis.npk.potassium / 300) * 100, 100) },
      ]
      : []

  // Disease progression timeline
  const timelineData = [
    { day: "Day 1", severity: isCrop ? analysis.severity * 0.5 : 0 },
    { day: "Day 3", severity: isCrop ? analysis.severity * 0.7 : 0 },
    { day: "Day 5", severity: isCrop ? analysis.severity : 0 },
    { day: "Day 7", severity: isCrop ? Math.max(analysis.severity - 10, 0) : 0 },
  ]

  const handleDownload = () => {
    const reportContent = `
AgroVision Analysis Report
--------------------------
Date: ${new Date(result.timestamp).toLocaleString()}
Type: ${isCrop ? "Crop Analysis" : "Soil Analysis"}

${isCrop ? `
Crop Detected: ${analysis.cropType}
Confidence: ${(analysis.confidence * 100).toFixed(1)}%
Condition: ${analysis.disease}
Disease Confidence: ${(analysis.diseaseConfidence * 100).toFixed(1)}%
Severity: ${analysis.severity.toFixed(1)}%
` : `
Soil Type: ${analysis.soilType}
Fertility Score: ${analysis.fertilityScore}/100
Moisture: ${analysis.moisture}
NPK Levels: N: ${analysis.npk?.n || 0}, P: ${analysis.npk?.p || 0}, K: ${analysis.npk?.k || 0}
`}

Recommendations:
${(analysis.recommendations || []).map((r: string) => `- ${r}`).join("\n")}

${isCrop && analysis.treatments ? `
Treatments:
${analysis.treatments.map((t: any) => `- ${t.name} (${t.dosage}, ${t.cost})`).join("\n")}
` : ""}
--------------------------
Generated by AgroVision AI
    `.trim()

    const blob = new Blob([reportContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `AgroVision_Report_${new Date().getTime()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      {/* Crop Image & Quick Stats */}
      <div className="grid md:grid-cols-3 gap-6">
        <div className="md:col-span-1">
          <div className="rounded-2xl overflow-hidden border-2 border-gray-200 dark:border-gray-700 shadow-lg">
            <img
              src={result.imageUrl || "/placeholder.svg"}
              alt="Analysis"
              className="w-full h-64 object-cover"
            />
          </div>
          <div className="mt-4 space-y-2 text-center">
            <p className="text-sm text-gray-600 dark:text-gray-400">Analyzed on</p>
            <p className="text-xs text-gray-500">{new Date(result.timestamp).toLocaleDateString()}</p>
          </div>
        </div>

        {/* Main Stats */}
        <div className="md:col-span-2 space-y-4">
          {/* Crop Type Card */}
          {isCrop && (
            <div className="bg-gradient-to-r from-green-50 to-emerald-50 dark:from-green-950 dark:to-emerald-950 rounded-2xl p-6 border-l-4 border-green-500">
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-sm text-gray-600 dark:text-gray-400">Detected Crop</p>
                  <h3 className="text-3xl font-bold text-green-700 dark:text-green-300 mt-1">
                    {analysis.cropType}
                  </h3>
                  <div className="flex items-center gap-2 mt-2">
                    <div className="w-2 h-2 rounded-full bg-green-500"></div>
                    <span className="text-sm text-green-600 dark:text-green-400">
                      {Math.round(analysis.confidence * 100)}% Match
                    </span>
                  </div>
                </div>
                <span className="text-5xl">🌾</span>
              </div>
            </div>
          )}

          {/* Disease / Soil Type Card */}
          <div
            className={`rounded-2xl p-6 border-l-4 ${isCrop
                ? `bg-gradient-to-r from-red-50 to-orange-50 dark:from-red-950 dark:to-orange-950 border-red-500`
                : `bg-gradient-to-r from-amber-50 to-yellow-50 dark:from-amber-950 dark:to-yellow-950 border-amber-500`
              }`}
          >
            <div className="flex items-start justify-between">
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  {isCrop ? "Disease Detected" : "Soil Type"}
                </p>
                <h3 className={`text-3xl font-bold mt-1 ${isCrop ? "text-red-700 dark:text-red-300" : "text-amber-700 dark:text-amber-300"}`}>
                  {isCrop ? analysis.disease : analysis.soilType}
                </h3>
                <div className="flex items-center gap-2 mt-2">
                  <div className={`w-2 h-2 rounded-full ${isCrop ? "bg-red-500" : "bg-amber-500"}`}></div>
                  <span className={`text-sm ${isCrop ? "text-red-600 dark:text-red-400" : "text-amber-600 dark:text-amber-400"}`}>
                    {isCrop
                      ? `${Math.round(analysis.diseaseConfidence * 100)}% Confidence`
                      : `Fertility: ${Math.round(analysis.fertilityScore * 10)}/10`}
                  </span>
                </div>
              </div>
              <span className="text-5xl">{isCrop ? "🦠" : "🌍"}</span>
            </div>
          </div>

          {/* Severity Meter (Crop) */}
          {isCrop && (
            <div className="bg-gradient-to-r from-slate-50 to-gray-50 dark:from-slate-900 dark:to-gray-900 rounded-2xl p-6 border-2 border-gray-200 dark:border-gray-700">
              <div className="flex items-center justify-between mb-3">
                <span className="text-sm font-semibold text-gray-700 dark:text-gray-300">Disease Severity</span>
                <span className={`text-2xl font-bold ${getSeverityColor(analysis.severity)}`}>
                  {Math.round(analysis.severity)}%
                </span>
              </div>
              <div className="w-full bg-gray-300 dark:bg-gray-600 rounded-full h-3 overflow-hidden">
                <div
                  className={`h-full transition-all ${analysis.severity < 30
                      ? "bg-gradient-to-r from-green-400 to-emerald-500"
                      : analysis.severity < 60
                        ? "bg-gradient-to-r from-yellow-400 to-orange-500"
                        : "bg-gradient-to-r from-red-400 to-rose-500"
                    }`}
                  style={{ width: `${analysis.severity}%` }}
                ></div>
              </div>
              <p className="text-xs text-gray-600 dark:text-gray-400 mt-2">
                {analysis.severity < 30
                  ? "✓ Plant is healthy"
                  : analysis.severity < 60
                    ? "⚠ Monitor closely"
                    : "⛔ Immediate action needed"}
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Interactive Charts */}
      <div className="grid md:grid-cols-2 gap-6">
        {/* Disease Timeline (Crop) */}
        {isCrop && (
          <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 border-2 border-gray-200 dark:border-gray-700 shadow-md">
            <h4 className="font-bold text-lg mb-4 text-gray-800 dark:text-gray-200">Disease Progression</h4>
            <ResponsiveContainer width="100%" height={250}>
              <BarChart data={timelineData}>
                <XAxis dataKey="day" stroke="#9ca3af" />
                <YAxis stroke="#9ca3af" />
                <Tooltip
                  contentStyle={{
                    backgroundColor: "#1f2937",
                    border: "1px solid #374151",
                    borderRadius: "8px",
                    color: "#fff",
                  }}
                />
                <Bar dataKey="severity" fill="#f59e0b" radius={[8, 8, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        )}

        {/* NPK Radar (Soil) */}
        {!isCrop && npkData.length > 0 && (
          <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 border-2 border-gray-200 dark:border-gray-700 shadow-md">
            <h4 className="font-bold text-lg mb-4 text-gray-800 dark:text-gray-200">NPK Balance</h4>
            <ResponsiveContainer width="100%" height={250}>
              <RadarChart data={npkData}>
                <PolarGrid stroke="#374151" />
                <PolarAngleAxis dataKey="name" stroke="#9ca3af" />
                <PolarRadiusAxis angle={90} domain={[0, 100]} stroke="#9ca3af" />
                <Radar name="Level %" dataKey="value" stroke="#10a853" fill="#10a853" fillOpacity={0.6} />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        )}

        {/* Recommendations */}
        <div className="bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-blue-950 dark:to-indigo-950 rounded-2xl p-6 border-2 border-blue-200 dark:border-blue-700">
          <div className="flex items-center gap-2 mb-4">
            <Target size={20} className="text-blue-600 dark:text-blue-400" />
            <h4 className="font-bold text-lg text-gray-800 dark:text-gray-200">Recommendations</h4>
          </div>
          <ul className="space-y-3">
            {(analysis.recommendations || []).slice(0, 4).map((rec: string, i: number) => (
              <li key={i} className="flex gap-3 text-sm">
                <CheckCircle size={16} className="text-green-600 dark:text-green-400 flex-shrink-0 mt-0.5" />
                <span className="text-gray-700 dark:text-gray-300">{rec}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Moisture / Treatments */}
        <div className="space-y-4">
          {!isCrop && analysis.moisture && (
            <div className="bg-gradient-to-br from-cyan-50 to-blue-50 dark:from-cyan-950 dark:to-blue-950 rounded-2xl p-6 border-2 border-cyan-200 dark:border-cyan-700">
              <div className="flex items-center gap-2 mb-3">
                <Droplets size={20} className="text-cyan-600 dark:text-cyan-400" />
                <h4 className="font-bold text-gray-800 dark:text-gray-200">Moisture Level</h4>
              </div>
              <p className="text-3xl font-bold text-cyan-700 dark:text-cyan-300">{analysis.moisture}</p>
              <p className="text-sm text-gray-600 dark:text-gray-400 mt-2">Optimal conditions maintained</p>
            </div>
          )}

          {isCrop && analysis.treatments && (
            <div className="bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-950 dark:to-pink-950 rounded-2xl p-6 border-2 border-purple-200 dark:border-purple-700">
              <div className="flex items-center gap-2 mb-3">
                <Leaf size={20} className="text-purple-600 dark:text-purple-400" />
                <h4 className="font-bold text-gray-800 dark:text-gray-200">Treatment Options</h4>
              </div>
              <ul className="space-y-2">
                {analysis.treatments.slice(0, 2).map((t: any, i: number) => (
                  <div key={i} className="text-sm">
                    <p className="font-semibold text-purple-700 dark:text-purple-300">{t.name}</p>
                    <p className="text-xs text-gray-600 dark:text-gray-400">
                      {t.dosage} • {t.cost}
                    </p>
                  </div>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>

      {/* Quick Actions */}
      <div className="flex gap-4 flex-wrap">
        <button
          onClick={handleDownload}
          className="px-6 py-3 rounded-lg bg-gradient-to-r from-green-500 to-emerald-600 text-white font-semibold hover:shadow-lg transition"
        >
          📥 Download Report
        </button>
        <button className="px-6 py-3 rounded-lg border-2 border-green-500 text-green-600 dark:text-green-400 font-semibold hover:bg-green-50 dark:hover:bg-green-950 transition">
          🔄 Analyze Again
        </button>
      </div>
    </div>
  )
}
